"""Search-only aliases (mostly French course terms). Not used for tagging, so they can't change which questions a topic covers."""
SYN = {
    'C.acs': ['infarctus', 'infarctus du myocarde', 'syndrome coronarien aigu', 'syndrome coronarien', 'heart attack', 'unstable angina', 'angor instable'],
    'C.ccs': ['angor', 'angine de poitrine', 'angina pectoris', 'coronaropathie'],
    'C.htn': ['hypertension arterielle', 'high blood pressure'],
    'C.aorta': ['anevrisme', 'anevrysme', 'anevrisme aortique', 'dissection aortique'],
    'C.pad': ['ischemie aigue', 'ischemie critique', 'arteriopathie oblitérante des membres inferieurs', 'limb ischemia'],
    'C.af': ['fibrillation auriculaire', 'fibrillation atriale'],
    'C.arf': ['rhumatisme articulaire aigu'],
    'C.chd': ['cardiopathie congenitale', 'cardiopathies congenitales', 'shunt', 'shunts', 'fallot'],
    'C.vte': ['maladie thromboembolique', 'thromboembolism'],
    'C.carotid': ['stenose carotidienne'],
    'C.mesenteric': ['angor mesenterique', 'ischemie intestinale'],
    'C.valves': ['valvulopathies', 'valve disease'],
    'D.hepatitis': ['hepatite virale', 'hepatites virales'],
    'D.hav': ['hepatite a'],
    'D.hbv': ['hepatite b'],
    'D.hcv': ['hepatite c'],
    'D.hev': ['hepatite e'],
    'D.peptic': ['ulcere', 'ulceres', 'ulcere duodenal', 'ulcere gastrique', 'ulcer'],
    'D.ugib': ['hemorragie digestive', 'hemorragie digestive haute', 'upper gi bleed'],
    'D.anal': ['hemorroides', 'fissure'],
    'D.biliary': ['lithiase biliaire', 'cholecystite', 'angiocholite', 'vesicule biliaire', 'gallbladder'],
    'D.pancreas': ['pancreatite chronique', 'pancreatite aigue', 'cancer du pancreas'],
    'D.colon': ['polypes', 'cancer colorectal', 'cancer du colon'],
    'D.eso-cancer': ['cancer de l oesophage', 'esophagus'],
    'D.gastric-cancer': ['cancer de l estomac'],
    'D.cirrhosis': ['liver failure', 'insuffisance hepatocellulaire'],
    'D.portal': ['varices oesophagiennes'],
    'D.peritonitis': ['peritoine'],
    'D.ibd': ['maladie inflammatoire', 'maladies inflammatoires chroniques de l intestin'],
    'D.caustic': ['ingestion de caustiques'],
    'D.hernia': ['hernie inguinale', 'eventration'],
    'E.gdm': ['diabete gestationnel'],
    'E.di': ['diabete insipide'],
    'E.dka': ['hypoglycemie', 'acidocetose diabetique'],
    'E.neuropathy': ['neuropathie diabetique', 'neuropathie', 'pied diabetique', 'diabetic foot'],
    'E.micro': ['retinopathie', 'retinopathie diabetique', 'nephropathie', 'nephropathie diabetique', 'microangiopathy'],
    'E.dm-cv': ['macroangiopathy', 'macroangiopathie', 'pied diabetique', 'diabetic foot'],
    'E.hyperthyroid': ['thyrotoxicose', 'maladie de basedow'],
    'E.hypothyroid': ['thyroidite de hashimoto'],
    'E.nodule': ['nodule thyroidien', 'cancer de la thyroide', 'nodule'],
    'E.prolactin': ['prolactinome', 'hyperprolactinemie'],
    'E.pituitary': ['adenome hypophysaire', 'hypophyse'],
    'E.hypopit': ['insuffisance hypophysaire', 'hypopituitarisme'],
    'E.addison': ['insuffisance surrenalienne', 'insuffisance surrenale aigue', 'adrenal crisis'],
    'E.cushing': ['syndrome de cushing', 'hypercorticisme'],
    'E.hypopara': ['hypoparathyroidie', 'tetanie'],
    'E.conn': ['hyperaldosteronisme'],
    'R.cancer': ['cancer du poumon', 'cancer bronchique', 'lung tumor', 'lung tumour'],
    'R.smoking': ['tabac', 'tabagisme', 'smoking', 'tobacco'],
    'R.trauma': ['traumatisme thoracique'],
    'R.resp-failure': ['insuffisance respiratoire aigue', 'ards'],
    'R.pneumothorax': ['pneumothorax spontane'],
    'S.fungal': ['teigne', 'mycose', 'candidose', 'candidiasis', 'onychomycosis', 'onychomycose', 'intertrigo'],
    'S.cancer': ['carcinome basocellulaire', 'carcinome epidermoide', 'cancer cutane'],
    'S.erysipelas': ['dermohypodermite'],
    'S.leish': ['bouton d orient', 'leishmaniose cutanee'],
    'S.urticaria': ['oedeme de quincke'],
    'S.bacterial': ['infections bacteriennes'],
    'S.syphilis': ['chancre mou'],
    'T.badnews': ['annonce', 'mauvaise nouvelle'],
    'T.empathy': ['empathie'],
}
ABBR = {
    'E.gdm': ['gdm'],
    'E.dm-tx': ['ado'],
}
